name: Deploy Backend

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}

    env: # Variables communes à toutes les étapes
      DB_PORT_INT: 5432
      DB_PORT_EXT: "${{ github.ref == 'refs/heads/master' && 5434 || 5433 }}"
      DB_NAME: "${{ github.ref == 'refs/heads/master' && 'postgres_prod' || 'postgres_dev' }}"
      DB_HOST: "${{ github.ref == 'refs/heads/master' && 'postgres_prod' || 'postgres_dev' }}"
      NETWORK: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'prod_network' || 'dev_network' }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DB_USERNAME: "${{ github.ref == 'refs/heads/master' && 'usr_db_prod' || 'usr_db_dev' }}"
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_CONTAINER_NAME: "${{ github.ref == 'refs/heads/master' && 'postgres_prod' || 'postgres_dev' }}"
      POSTGRES_VOLUME: "${{ github.ref == 'refs/heads/master' && 'postgres_data_prod' || 'postgres_data_dev' }}"
      CONTAINER_NAME: "${{ github.ref == 'refs/heads/master' && 'back_node_prod' || 'back_node_dev' }}"
      MOUNT_PATH: "${{ github.ref == 'refs/heads/master' && '/home/prod.alxmultimedia.com/backend' || '/home/dev.alxmultimedia.com/backend' }}"
      DATABASE_URL: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@${{ github.ref == 'refs/heads/master' && 'postgres_prod' || 'postgres_dev' }}:${DB_PORT_INT}/${DB_NAME}"
      BACKEND_PORT: "${{ secrets.PORT }}"

    steps:
      # Étape 1 - Checkout du dépôt Git
      - name: 1 - Checkout repository
        uses: actions/checkout@v3

      # Étape 2 - Build Docker image for backend
      - name: 2 - Build Docker image
        env:
          DOCKER_NAME: "back_node:latest"
        run: docker build -t $DOCKER_NAME -f Dockerfile.backend .

      # Étape 3 : Push Docker image to registry (optionnel)
      - name: 3 - Push Docker image to registry
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [ -n "$DOCKER_REGISTRY" ]; then
            echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
            docker tag back_node:latest $DOCKER_REGISTRY/$DOCKER_USERNAME/back_node:latest
            docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/back_node:latest
          else
            echo "DOCKER_REGISTRY is not defined. Skipping Docker push."
          fi

      # Étape 4 - Start SSH agent and add key
      - name: 4 - Start SSH agent and add key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/git_id_rsa
          chmod 600 /tmp/git_id_rsa
          eval $(ssh-agent -s)
          ssh-add /tmp/git_id_rsa

      # Étape 5 - Démarrage de PostgreSQL
      - name: 5 - Start PostgreSQL container
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            docker volume create $POSTGRES_VOLUME || true &&
            docker pull postgres:13 &&
            docker stop $POSTGRES_CONTAINER_NAME || true &&
            docker rm $POSTGRES_CONTAINER_NAME || true &&
            docker run -d --name $POSTGRES_CONTAINER_NAME \
              --network $NETWORK \
              -e POSTGRES_USER=$DB_USERNAME \
              -e POSTGRES_PASSWORD=$DB_PASSWORD \
              -e POSTGRES_DB=$DB_NAME \
              -v $POSTGRES_VOLUME:/var/lib/postgresql/data \
              -p $DB_PORT_EXT:$DB_PORT_INT \
              postgres:13
          "

      # Étape 6 - Créer la base de données et l'utilisateur
      - name: 6 - Create database and user
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            echo '*** DEBUGGING VARIABLES AND SECRETS ***' &&
            echo 'DB_NAME: $DB_NAME' &&
            echo 'POSTGRES_CONTAINER_NAME: $POSTGRES_CONTAINER_NAME' &&
            echo 'DB_HOST: $DB_HOST' &&
            echo 'DB_PORT_INT: $DB_PORT_INT' &&
            echo 'DB_PORT_EXT: $DB_PORT_EXT' &&
            echo 'NETWORK: $NETWORK' &&
            echo 'Secrets.DB_USERNAME: $DB_USERNAME' &&
            echo 'Secrets.DB_PASSWORD: $DB_PASSWORD' &&

            echo 'Checking and creating database and user if not exists...' &&

            # Générer le script SQL pour la création de l'utilisateur
            cat <<EOF > /tmp/init_user.sql
            DO \$\$
            BEGIN
              IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_USERNAME') THEN
                CREATE ROLE $DB_USERNAME WITH LOGIN PASSWORD '$DB_PASSWORD';
              END IF;
            END
            \$\$;
            EOF

            # Générer le script SQL pour la création de la base de données
            cat <<EOF > /tmp/init_database.sql
            DO \$\$
            BEGIN
              IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME') THEN
                CREATE DATABASE $DB_NAME WITH OWNER = '$DB_USERNAME';
              END IF;
            END
            \$\$;
            EOF

            # Exécuter les scripts SQL
            docker cp /tmp/init_user.sql $POSTGRES_CONTAINER_NAME:/tmp/init_user.sql &&
            docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -f /tmp/init_user.sql &&

            docker cp /tmp/init_database.sql $POSTGRES_CONTAINER_NAME:/tmp/init_database.sql &&
            docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -f /tmp/init_database.sql

            
            # Nettoyage des fichiers temporaires
            rm /tmp/init_user.sql /tmp/init_database.sql
          "

      # Étape 7 - Déployer le conteneur Backend
      - name: 7 - Deploy Backend container
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            docker stop $CONTAINER_NAME || true &&
            docker rm $CONTAINER_NAME || true &&
            docker run -d --name $CONTAINER_NAME \
              --network $NETWORK \
              -e DATABASE_URL=\"$DATABASE_URL\" \
              -e NODE_ENV=\"${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}\" \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -v $MOUNT_PATH:/app \
              -w /app \
              -p $BACKEND_PORT:7000 \
              back_node:latest
          "

      # Étape 8 - Set Remote Git URL
      - name: 8 - Set Remote Git URL
        run: git remote set-url origin ${{ secrets.GIT_REPO_URL }}

      # Étape 9 - Health Check
      - name: 9 - Health Check
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            curl http://localhost:$BACKEND_PORT/api/health || exit 1
          "
