name: Déployer Backend

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}

    env:
      ENV: ${{ vars.ENV }}
      DB_PORT_INT: ${{ vars.DB_PORT_INT }}
      DB_PORT_EXT: ${{ vars.DB_PORT_EXT }}
      BACKEND_PORT: ${{ vars.BACKEND_PORT }}
      DB_NAME: ${{ vars.DB_POST }}_${{ vars.ENV }}
      DB_HOST: ${{ vars.DB_POST }}_${{ vars.ENV }}
      NETWORK: ${{ vars.NET }}_${{ vars.ENV }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DB_USERNAME: ${{ vars.USR_DB }}_${{ vars.ENV }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_CONTAINER_NAME: ${{ vars.DB_POST }}_${{ vars.ENV }}
      POSTGRES_VOLUME: ${{ vars.DB_POST }}_${{ vars.DATA }}_${{ vars.ENV }}
      CONTAINER_NAME: ${{ vars.BACK }}_${{ vars.NODE }}_${{ vars.ENV }}
      MOUNT_PATH: ${{ secrets.MOUNT_PATH }}
      DATABASE_URL: "postgresql://$DB_USERNAME:${{ secrets.DB_PASSWORD }}@$DB_HOST:$DB_PORT_INT/$DB_NAME"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DOCKER_NAME: back_node:latest

    steps:
      # Étape 1 - Afficher les variables générées
      - name: 1 - Afficher les variables générées
        run: |
          mkdir -p backend/logs
          echo "=== Déploiement Backend : $(date) ===" | tee backend/logs/backend_deploy.log
          echo "Environnement : $ENV" | tee -a backend/logs/backend_deploy.log
          echo "Nom de la base de données : $DB_NAME" | tee -a backend/logs/backend_deploy.log
          echo "Hôte de la base de données : $DB_HOST" | tee -a backend/logs/backend_deploy.log
          echo "Nom du conteneur PostgreSQL : $POSTGRES_CONTAINER_NAME" | tee -a backend/logs/backend_deploy.log
          echo "Nom de l'utilisateur : $DB_USERNAME" | tee -a backend/logs/backend_deploy.log
          echo "URL de connexion à la base : $DATABASE_URL" | tee -a backend/logs/backend_deploy.log

      # Étape 2 - Récupérer le dépôt Git
      - name: 2 - Récupérer le dépôt
        uses: actions/checkout@v3

      # Étape 2.5 - Configurer la version de Node.js
      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Étape 3 - Installer les dépendances et corriger les vulnérabilités
      - name: 3 - Installer les dépendances et corriger les vulnérabilités
        run: |
          npm install --production | tee -a backend/logs/backend_deploy.log
          npm audit fix | tee -a backend/logs/backend_deploy.log

      # Étape 4 - Construire l'image Docker pour le backend
      - name: 4 - Construire l'image Docker
        run: |
          docker build -t $DOCKER_NAME -f Dockerfile.backend . | tee -a backend/logs/backend_deploy.log

      # Étape 5 - Démarrer l'agent SSH et ajouter la clé
      - name: 5 - Démarrer l'agent SSH et ajouter la clé
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/git_id_rsa
          chmod 600 /tmp/git_id_rsa
          eval $(ssh-agent -s)
          ssh-add /tmp/git_id_rsa

      # Étape 6 - Démarrer le conteneur PostgreSQL
      - name: 6 - Démarrer le conteneur PostgreSQL
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            # Vérifier et créer le réseau si nécessaire
            if ! docker network ls --filter \"name=^$NETWORK\$\" --format '{{.Name}}' | grep -w $NETWORK; then
              docker network create $NETWORK
            fi

            # Vérifier et créer le volume si nécessaire
            if ! docker volume ls --filter \"name=^$POSTGRES_VOLUME\$\" --format '{{.Name}}' | grep -w $POSTGRES_VOLUME; then
              docker volume create $POSTGRES_VOLUME
            fi

            # Arrêter et supprimer le conteneur existant, si nécessaire
            docker ps -a --filter \"name=$POSTGRES_CONTAINER_NAME\" --format '{{.Names}}' | grep -w $POSTGRES_CONTAINER_NAME && docker stop $POSTGRES_CONTAINER_NAME || true
            docker ps -a --filter \"name=$POSTGRES_CONTAINER_NAME\" --format '{{.Names}}' | grep -w $POSTGRES_CONTAINER_NAME && docker rm $POSTGRES_CONTAINER_NAME || true

            # Mettre à jour l'image PostgreSQL
            docker pull postgres:13

            # Lancer un nouveau conteneur PostgreSQL
            docker run -d --name $POSTGRES_CONTAINER_NAME \
              --network $NETWORK \
              -e POSTGRES_USER=$DB_USERNAME \
              -e POSTGRES_PASSWORD=$DB_PASSWORD \
              -e POSTGRES_DB=$DB_NAME \
              -v $POSTGRES_VOLUME:/var/lib/postgresql/data \
              -p $DB_PORT_EXT:$DB_PORT_INT \
              postgres:13

            # Vérifier l'état du conteneur
            echo 'Vérification de l\'état du conteneur PostgreSQL :'
            docker ps --filter \"name=$POSTGRES_CONTAINER_NAME\"
          " | tee -a backend/logs/backend_deploy.log

      # Étape 6.1 - Nettoyer les anciens backups
      - name: 6.1 - Nettoyer les anciens backups (Prod uniquement)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            find /root -name 'prod_backup_*.sql' -type f -mtime +7 -exec rm -f {} \;
          " | tee -a backend/logs/backend_deploy.log

      # Étape 6.2 - Sauvegarder la base de données
      - name: 6.2 - Sauvegarder la base de données (Prod uniquement)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            docker exec $POSTGRES_CONTAINER_NAME pg_dump -U $DB_USERNAME $DB_NAME > /root/prod_backup_$(date +%Y%m%d%H%M%S).sql
          " | tee -a backend/logs/backend_deploy.log

      # Étape 7 - Créer la base de données et l'utilisateur démo
      - name: 7 - Créer la base de données et l'utilisateur démo
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -c \"
              DROP DATABASE IF EXISTS $DB_NAME;
              CREATE DATABASE $DB_NAME WITH OWNER $DB_USERNAME;
              DROP ROLE IF EXISTS $DB_USERNAME;
              CREATE ROLE $DB_USERNAME WITH LOGIN PASSWORD '$DB_PASSWORD';
              GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;
            \"
          " | tee -a backend/logs/backend_deploy.log

      # Étape 8 - Déployer le conteneur Backend
      - name: 8 - Déployer le conteneur Backend
        run: |
          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
            docker ps -a --filter \"name=$CONTAINER_NAME\" --format '{{.Names}}' | grep -w $CONTAINER_NAME && docker stop $CONTAINER_NAME || true &&
            docker ps -a --filter \"name=$CONTAINER_NAME\" --format '{{.Names}}' | grep -w $CONTAINER_NAME && docker rm $CONTAINER_NAME || true &&
            docker run -d --name $CONTAINER_NAME \
              --network $NETWORK \
              -e DATABASE_URL=\"$DATABASE_URL\" \
              -e NODE_ENV=$ENV \
              -e JWT_SECRET=$JWT_SECRET \
              -v $MOUNT_PATH:/app \
              -w /app \
              -p $BACKEND_PORT:7000 \
              back_node:latest
          " | tee -a backend/logs/backend_deploy.log

      # Étape 9 - Configurer l'URL Git distante
      - name: 9 - Configurer l'URL Git distante
        run: git remote set-url origin ${{ secrets.GIT_REPO_URL }}
